### ISSUE TITLE
repository plan

### ISSUE THREAD

**Issue by dsdanielpark** [dsdanielpark/multi-objective-recommender#1]
- [x] Define problem clearly
- [x] Check data quality
- [x] Analysis data
- [x] Experiment palnning
- [x] Check result 
- [x] Experiment more if you wish
- [x] Check result 
- [x] Get pipeline
- [x] Check model
- [x] Inference and result quality check
- [x] Submission done (6days to go)
- [ ] Result visuallization
- [ ] Refactoring
- [ ] Publish
- [ ] Close issue

**Comment by DSDanielPark** [comment]
`PAUSE` private repository 타사 과제 전형 진행 중으로 레포지토리 업데이트 일시 중지 (23.02.10~23.02.16)

**Comment by DSDanielPark** [comment]
N사 과제 전형 및 A사 면접 전형 완료로 레포 재계(23.02.23), 2월 중 코드 래핑해서 마감 목표
